# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/myrrkel/Workspace/Qt/pyzic/dialogmusicdirectories.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(622, 223)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.wLeft = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wLeft.sizePolicy().hasHeightForWidth())
        self.wLeft.setSizePolicy(sizePolicy)
        self.wLeft.setMinimumSize(QtCore.QSize(206, 0))
        self.wLeft.setObjectName("wLeft")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wLeft)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.DirListView = QtWidgets.QListView(self.wLeft)
        self.DirListView.setObjectName("DirListView")
        self.verticalLayout_3.addWidget(self.DirListView)
        self.wButtonsList = QtWidgets.QWidget(self.wLeft)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wButtonsList.sizePolicy().hasHeightForWidth())
        self.wButtonsList.setSizePolicy(sizePolicy)
        self.wButtonsList.setMinimumSize(QtCore.QSize(206, 29))
        self.wButtonsList.setMaximumSize(QtCore.QSize(16777215, 29))
        self.wButtonsList.setObjectName("wButtonsList")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.wButtonsList)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.AddButton = QtWidgets.QPushButton(self.wButtonsList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        self.AddButton.setMinimumSize(QtCore.QSize(100, 0))
        self.AddButton.setSizeIncrement(QtCore.QSize(25, 0))
        self.AddButton.setObjectName("AddButton")
        self.horizontalLayout_3.addWidget(self.AddButton)
        self.DeleteButton = QtWidgets.QPushButton(self.wButtonsList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DeleteButton.sizePolicy().hasHeightForWidth())
        self.DeleteButton.setSizePolicy(sizePolicy)
        self.DeleteButton.setMinimumSize(QtCore.QSize(100, 0))
        self.DeleteButton.setSizeIncrement(QtCore.QSize(75, 0))
        self.DeleteButton.setObjectName("DeleteButton")
        self.horizontalLayout_3.addWidget(self.DeleteButton)
        self.verticalLayout_3.addWidget(self.wButtonsList)
        self.horizontalLayout.addWidget(self.wLeft)
        self.wRight = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wRight.sizePolicy().hasHeightForWidth())
        self.wRight.setSizePolicy(sizePolicy)
        self.wRight.setMinimumSize(QtCore.QSize(350, 0))
        self.wRight.setObjectName("wRight")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wRight)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wLabels = QtWidgets.QWidget(self.wRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.wLabels.sizePolicy().hasHeightForWidth())
        self.wLabels.setSizePolicy(sizePolicy)
        self.wLabels.setObjectName("wLabels")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wLabels)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelName = QtWidgets.QLabel(self.wLabels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelName.sizePolicy().hasHeightForWidth())
        self.labelName.setSizePolicy(sizePolicy)
        self.labelName.setMinimumSize(QtCore.QSize(0, 25))
        self.labelName.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.labelDir = QtWidgets.QLabel(self.wLabels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDir.sizePolicy().hasHeightForWidth())
        self.labelDir.setSizePolicy(sizePolicy)
        self.labelDir.setMinimumSize(QtCore.QSize(0, 25))
        self.labelDir.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelDir.setObjectName("labelDir")
        self.verticalLayout.addWidget(self.labelDir)
        self.labelStyle = QtWidgets.QLabel(self.wLabels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStyle.sizePolicy().hasHeightForWidth())
        self.labelStyle.setSizePolicy(sizePolicy)
        self.labelStyle.setMinimumSize(QtCore.QSize(0, 25))
        self.labelStyle.setMaximumSize(QtCore.QSize(16777215, 25))
        self.labelStyle.setObjectName("labelStyle")
        self.verticalLayout.addWidget(self.labelStyle)
        self.horizontalLayout_2.addWidget(self.wLabels)
        self.wDirEdits = QtWidgets.QWidget(self.wRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.wDirEdits.sizePolicy().hasHeightForWidth())
        self.wDirEdits.setSizePolicy(sizePolicy)
        self.wDirEdits.setObjectName("wDirEdits")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wDirEdits)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Name = QtWidgets.QLineEdit(self.wDirEdits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Name.sizePolicy().hasHeightForWidth())
        self.Name.setSizePolicy(sizePolicy)
        self.Name.setMinimumSize(QtCore.QSize(25, 0))
        self.Name.setMaximumSize(QtCore.QSize(16777215, 25))
        self.Name.setObjectName("Name")
        self.verticalLayout_2.addWidget(self.Name)
        self.DirWidget = QtWidgets.QWidget(self.wDirEdits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.DirWidget.sizePolicy().hasHeightForWidth())
        self.DirWidget.setSizePolicy(sizePolicy)
        self.DirWidget.setMinimumSize(QtCore.QSize(0, 25))
        self.DirWidget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.DirWidget.setObjectName("DirWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.DirWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.DirEdit = QtWidgets.QLineEdit(self.DirWidget)
        self.DirEdit.setMinimumSize(QtCore.QSize(25, 0))
        self.DirEdit.setMaximumSize(QtCore.QSize(16777215, 25))
        self.DirEdit.setObjectName("DirEdit")
        self.gridLayout.addWidget(self.DirEdit, 0, 0, 1, 1)
        self.DirButton = QtWidgets.QPushButton(self.DirWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DirButton.sizePolicy().hasHeightForWidth())
        self.DirButton.setSizePolicy(sizePolicy)
        self.DirButton.setMinimumSize(QtCore.QSize(25, 25))
        self.DirButton.setMaximumSize(QtCore.QSize(25, 25))
        self.DirButton.setObjectName("DirButton")
        self.gridLayout.addWidget(self.DirButton, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.DirWidget)
        self.DirStyle = QtWidgets.QComboBox(self.wDirEdits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.DirStyle.sizePolicy().hasHeightForWidth())
        self.DirStyle.setSizePolicy(sizePolicy)
        self.DirStyle.setMinimumSize(QtCore.QSize(0, 25))
        self.DirStyle.setMaximumSize(QtCore.QSize(16777215, 25))
        self.DirStyle.setObjectName("DirStyle")
        self.verticalLayout_2.addWidget(self.DirStyle)
        self.horizontalLayout_2.addWidget(self.wDirEdits)
        self.horizontalLayout.addWidget(self.wRight)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AddButton.setText(_translate("Dialog", "Add directory"))
        self.DeleteButton.setText(_translate("Dialog", "Delete"))
        self.labelName.setText(_translate("Dialog", "Name"))
        self.labelDir.setText(_translate("Dialog", "Dir"))
        self.labelStyle.setText(_translate("Dialog", "Style"))
        self.DirButton.setText(_translate("Dialog", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

